# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sachin Kharude
tagline:          'Software Engineer'
description:      'I am currently working as Senior Software Engineer at HERE Technologies.'
url:              https://sackh.github.io
baseurl:          /

author:
  name:           'Sachin Kharude'
  url:            https://sackh.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sackh/sackh.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
